version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
  # Define the jobs we want to run for this project
jobs:
   # Exercise: Config and Deployment
  print_greetings:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
      - run: echo HELLO
      - run: echo WORLD
      - run: echo $_env_name 
   
  configure_infrastructure: 
    docker:
      #- image: python:3.7-alpine3.11
      - image: python:3.11-rc-alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["77:e0:f1:03:ec:19:95:f7:0d:31:b3:f1:ad:0d:39:85"]
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible 
      - run:
          name: Configure server
          command: | 
            echo kapil
            ansible-playbook -i inventory.txt main-remote.yml
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- print_greetings
      - configure_infrastructure
      #- myjob2
